platform :ios, '15.0'
use_frameworks!

target 'Diploma' do
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'
  pod 'Firebase/Analytics'
  
  # Google Sign In
  pod 'GoogleSignIn'
  
  # Firebase UI
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
end 